package skal.tools.DHBot;

public enum ScoutResultStatusCodes
{ 
	SUCCESS,
	ERROR_SETUP_EMULATOR_WINDOW,
	ERROR_DEFINE_REGIONS,
	ERROR_READ_GLORY,
	ERROR_MAX_GOLD_SPENT,
	ERROR_UNDEFINED, CANCELLED,
}